### ISSUE TITLE
Setting breakpoints in Modules does not work

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/poshtools-issues#11]
Dbatools. We have functions in individual files. We dot source them for dev and add breakpoint to a given ps1 file, breakpoint is never hit. Debugger starts and then just stops immediately.

**Comment by adamdriscoll** [comment]
Get-PSBreakpoint doesn't return anything after setting a breakpoint in the module.

**Comment by wsmelton** [comment]
Tested this on a new Script project and the debugger does not seem to want to attach either.

Just created a PowerShellProject.ps1 and added this code with a breakpoint on line 6:

[cmdletbinding()]
param(
	$i
)
foreach ($i in $list) {
	(Get-Process)[$i]
}
Hitting F5 or starting the debugger it just flashes open and then closes in VS for some reason. I've enabled diagnostics, but I do not find where that data is being written.

**Comment by adamdriscoll** [comment]
@wsmelton - Can you upgrade to version 5.3.5 and send me the logs? I've fixed an issue where half the logs were missing. You should see logs in %AppData%\PowerShell Tools for Visual Studio. You may need to restart VS after enabling diagnostics.

**Comment by wsmelton** [comment]
Right now, not sure what configuration I changed but VS hoses up when I try to get into the configuration for the extension...trying to figure out how to reset that configuration so it stops doing whatever I turned on 😁

**Comment by wsmelton** [comment]
I don't see any log in the location when I'm trying to debug a function in a folder opened in VS 2019.


![vs_pro_tools](https://user-images.githubusercontent.com/11204251/75575212-5b48aa00-5a25-11ea-8700-eb37fd3e3e1f.gif)

**Comment by wsmelton** [comment]
[log.devenv.exe.txt](https://github.com/ironmansoftware/poshtools-issues/files/4268522/log.devenv.exe.txt)

Log finally generated after a few restarts of VS.

**Comment by wsmelton** [comment]
[log.devenv.exe.txt](https://github.com/ironmansoftware/poshtools-issues/files/4268561/log.devenv.exe.txt)

Setting the breakpoint at line 1 (and 9 is still there)...debugger repeats as just starting and then immediately stopping.

**Comment by wsmelton** [comment]
[log.devenv.exe.txt](https://github.com/ironmansoftware/poshtools-issues/files/4268605/log.devenv.exe.txt)

**Comment by adamdriscoll** [comment]
Oooo. This time we've got errors. Can you try to turn off the Set Runspace Execution Policy in the options for PoshTools? Is there a log.powershell.exe.txt? 

```
[22] ERROR PowerShellTools.DebugEngine.Engine (null) - Failed to start debugging. 
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PowerShellTools.ServiceManagement.PowerShellDebuggingServiceProxy.<SetRunspaceAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PowerShellTools.DebugEngine.Engine.<ExecuteAsync>d__14.MoveNext()
[22] DEBUG PowerShellTools.DebugEngine.EngineEvents (null) - ProgramDestroyed
[1] DEBUG PowerShellTools.DebugEngine.ScriptBreakpoint (null) - ScriptBreakpoint: Delete
[1] DEBUG PowerShellTools.DebugEngine.EngineEvents (null) - BreakpointRemoved
[1] INFO  PowerShellTools.DebugEngine.BreakpointManager (null) - RemoveBreakpoint: C:\git\dbatools\functions\Get-DbaDiskSpace.ps1 116 30
[1] DEBUG PowerShellTools.ServiceManagement.PowerShellDebuggingServiceProxy (null) - GetTrueFileName(C:\git\dbatools\functions\Get-DbaDiskSpace.ps1)
[1] DEBUG PowerShellTools.ServiceManagement.PowerShellDebuggingServiceProxy (null) - GetRunspaceAvailability()
[1] DEBUG PowerShellTools.ServiceManagement.PowerShellDebuggingServiceProxy (null) - RemoveBreakpoint({"ScriptFullPath":"C:\\git\\dbatools\\functions\\Get-DbaDiskSpace.ps1","Line":116,"Column":30})
[1] ERROR PowerShellTools.DebugEngine.BreakpointManager (null) - Failed to remove breakpoint.
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at HostProtocol.PowerShellDebuggingServiceGrpc.PowerShellDebuggingServiceGrpcClient.RemoveBreakpoint(PowerShellBreakpointMessage request, CallOptions options)
   at HostProtocol.PowerShellDebuggingServiceGrpc.PowerShellDebuggingServiceGrpcClient.RemoveBreakpoint(PowerShellBreakpointMessage request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at PowerShellTools.ServiceManagement.PowerShellDebuggingServiceProxy.RemoveBreakpoint(PowerShellBreakpoint bp)
   at PowerShellTools.DebugEngine.BreakpointManager.RemoveBreakpoint(ScriptBreakpoint breakpoint)
```

**Comment by adamdriscoll** [comment]
Just validating that this does work in some circumstances....I'm not totally crazy. 

![dtUtzBde1d](https://user-images.githubusercontent.com/1256531/75579894-fc366580-5a23-11ea-87ef-d0b93d032a8e.gif)

**Comment by wsmelton** [comment]
I don't see any option for `Set Runspace Execution Policy`.

**Comment by wsmelton** [comment]
This is the result I get trying to set a breakpoint in a given psm1 file:
![image](https://user-images.githubusercontent.com/11204251/75584272-00b74a00-5a35-11ea-9528-03d4f5b24345.png)
