### ISSUE TITLE
VS Code Error on Refresh

### ISSUE THREAD

**Issue by benconaway** [ironmansoftware/poshtools-issues#22]
Cannot use variable explorer in Visual Studio code.  Ensured I had proper versions of .Net and PowerShell 7 installed.  No variables appear, and clicking on the refresh icon gives me an error. 
 Error details: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at PowerShellToolsPro.Cmdlets.GetVariables.Execute(String input, Runspace runspace) in D:\a\1\s\PowerShellToolsPro.Cmdlets\VSCodeHelpers.cs:line 200
   at PowerShellToolsPro.Cmdlets.VSCodeHelpers.StartServer(String psScriptRoot) in D:\a\1\s\PowerShellToolsPro.Cmdlets\VSCodeHelpers.cs:line 127

**Comment by adamdriscoll** [comment]
We are seeing the same issue. The redesign of the PowerShell extension caused this issue so we are looking for a solution.

**Comment by adamdriscoll** [comment]
This has been resolved in version 5.8.6.

**Comment by benconaway** [comment]
5.8.6 variable explorer in VS Code works!  I can't thank you enough.  This feature makes the purchase of Pro Tools worth it to me.
