### ISSUE TITLE
PSScriptPad x64 crashes when using SaveAs dialog

### ISSUE THREAD

**Issue by Atreidae** [ironmansoftware/poshtools-issues#79]
**App Version:** PSScriptPadx64 5.8.2 
**OS**: Win10 20H2
Also Tested on 5.5.1 and cant replicate the issue.

To replicate, Open a file in PSScriptPad using the open command bar button, then attempt to save the file using SaveAs command bar button.
it doesn't matter if
- you create a new file
- you overwrite a different file
- you save as the existing filename

All three cause PSScriptPad to crash with no error message or prompt.
However, if you create a new file, then "SaveAs" this works fine.
Opening the same file and SaveAs again will crash PSScriptPad

(two examples in this video)
https://user-images.githubusercontent.com/8736291/103146424-37690880-479d-11eb-9086-8c3cbb87de87.mp4

Windows Error Reporting Dump

[Report.zip](https://github.com/ironmansoftware/poshtools-issues/files/5742749/Report.zip)

### Event Logs 

**Event 1026 .NET Runtime**
 `Application: PSScriptPad.x64.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at ActiproSoftware.Text.Utility.PropertyDictionary.Add(System.Object, System.Object)
   at FormDesigner.Host.ViewModels.PowerShellTabViewModel.Save(Boolean)
   at FormDesigner.Host.MainWindow.<.ctor>b__15_1(System.Object, ActiproSoftware.Windows.Controls.Ribbon.Controls.ExecuteRoutedEventArgs)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.RoutedEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at ActiproSoftware.Windows.Controls.Ribbon.Controls.Primitives.ControlBase.OnClick(ActiproSoftware.Windows.Controls.Ribbon.Controls.ExecuteRoutedEventArgs)
   at ActiproSoftware.Windows.Controls.Ribbon.Controls.Primitives.ButtonBase.OnClick(ActiproSoftware.Windows.Controls.Ribbon.Controls.ExecuteRoutedEventArgs)
   at ActiproSoftware.Windows.Controls.Ribbon.Controls.Primitives.ControlBase+<>c__DisplayClass112_0.<RaiseClickEvent>b__0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at FormDesigner.Host.App.Main()

`
**Event 1000 Application Error**
`Faulting application name: PSScriptPad.x64.exe, version: 5.7.14.0, time stamp: 0xc7deafb7
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xec58f015
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x8aec
Faulting application start time: 0x01d6db4e5decc690
Faulting application path: C:\Users\Atreidae\OneDrive\Desktop\PSScriptPad.x64.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7dc431d2-c223-4c91-a9ed-aa2b78c65b11
Faulting package full name: 
Faulting package-relative application ID: `

**Event 1001 Windows Error Reporting**
`

Fault bucket 1630370836307779744, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: PSScriptPad.x64.exe
P2: 5.7.14.0
P3: c7deafb7
P4: mscorlib
P5: 4.8.4300.0
P6: 5f7e60da
P7: 339
P8: 10
P9: System.ArgumentException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD448.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD831.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD861.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD86F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD89F.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_PSScriptPad.x64._1ece109c686663ba297e5d897644181fbc337b_04d3e80f_1e51d6ca-1831-45a4-a484-ce082d31573f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7dc431d2-c223-4c91-a9ed-aa2b78c65b11
Report Status: 268435456
Hashed bucket: 1fd6e2d5e1aaeedcb6a03da3364820a0
Cab Guid: 0
`

**Comment by adamdriscoll** [comment]
Thanks for all the info! This has been resolved in 5.8.3
